// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBcvPdEMvB-X-rAJNFuvqoWHuvWhkz5jg',
    appId: '1:303552525092:web:9a54fb7d6f543251fa79b1',
    messagingSenderId: '303552525092',
    projectId: 'shifahwellness-citydoctor',
    authDomain: 'shifahwellness-citydoctor.firebaseapp.com',
    databaseURL: 'https://shifahwellness-citydoctor-default-rtdb.firebaseio.com',
    storageBucket: 'shifahwellness-citydoctor.appspot.com',
    measurementId: 'G-G0LBWR8FT5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgI44b9L4YWrRnXV4CjmeG5AXY5jL4TSU',
    appId: '1:303552525092:android:9d3b10149ccfa22ffa79b1',
    messagingSenderId: '303552525092',
    projectId: 'shifahwellness-citydoctor',
    databaseURL: 'https://shifahwellness-citydoctor-default-rtdb.firebaseio.com',
    storageBucket: 'shifahwellness-citydoctor.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi68L_ifmxYXABSkHWZN7yXmagLrRpRXI',
    appId: '1:303552525092:ios:9a36dc9f59fa470efa79b1',
    messagingSenderId: '303552525092',
    projectId: 'shifahwellness-citydoctor',
    databaseURL: 'https://shifahwellness-citydoctor-default-rtdb.firebaseio.com',
    storageBucket: 'shifahwellness-citydoctor.appspot.com',
    androidClientId: '303552525092-1sv4iluogovnn3cgup2ds8rksb05kdet.apps.googleusercontent.com',
    iosClientId: '303552525092-ecr2l0kjoeeggcia36h9fmhntopj9lar.apps.googleusercontent.com',
    iosBundleId: 'com.citydoctorapp.medicadmin',
  );
}
